library(shiny)

shinyUI(pageWithSidebar(
    headerPanel("Precision statistics"),
    sidebarPanel(
        p(paste("Produce ETA predictions of various quality by changing the parameters below ",
                "and explore the output of various measures of the prediction accuracy.")),
        sliderInput("n", "Number of ETAs predicted", 
                    min = 0, max = 100000, value = 100, 
                    step = 1000, ticks = 5000, 
                    round = TRUE, animate = TRUE),
        sliderInput("precision", "Precision (factor)", 
                    min = 0, max = 2, value = .0, 
                    step = .05, ticks = .2),
        sliderInput("noise", "Noise (minutes)", 
                    min = 0, max = 60, value = .0, 
                    step = 2, ticks = 10),
        sliderInput("bias_factor", "Bias (factor)", 
                    min = -1, max = 1, value = .0, 
                    step = .1, ticks = .1),
        sliderInput("bias_constant", "Bias (constant)", 
                    min = -60, max = 60, value = .0, 
                    step = 10, ticks = 10),
        checkboxInput("outliers", "Add outliers", value = FALSE)
    ),
    mainPanel(
        tabsetPanel(type = "tabs", selected = "Raw",
          tabPanel("Histogram", 
                   p(paste("Histogram of predictions with a real value between 50 to 60 minutes")),
                   plotOutput("histogram", height="540px")),
          tabPanel("Density", 
                   p(paste("A kernel density plot of predictions with a real value between 50 to 60 minutes")),
                   plotOutput("density", height="540px")),
          tabPanel("Raw", 
                   p(paste("All predictions. It is difficult to see the overall behaviour of the predictions, ",
                           "but it gives a good overview.")),
                   plotOutput("raw", height="540px")),
          tabPanel("Raw (error)", 
                   p(withMathJax(paste("The error of each prediction $$value_t = real_t - prediction_t$$"))),
                   plotOutput("rawError", height="540px")),
          tabPanel("Grouped (mean)", 
                   p(withMathJax(paste("Mean value grouped by minute of real value."))),
                   plotOutput("grouped", height="540px")),
          tabPanel("Bias", 
                   p(withMathJax(paste("Bias, grouped by minute of real value. "))),
                   plotOutput("bias", height="540px")),
          tabPanel("MAE", 
                   p(withMathJax(paste("Mean absolute error, grouped by minute of real value. Outliers can ",
                                       "get lost in the noise."))),
                   plotOutput("mae", height="540px")),
          tabPanel("RMSE", 
                   p(withMathJax(paste("Root Mean Square Error, grouped by minute of real value. ",
                                       "More sensitive to outliers"))),
                   plotOutput("rmse", height="540px")),
          tabPanel("MAPE", 
                   p(withMathJax(paste("Mean absolute precision error, grouped by minute of real value. ",
                                       "Calculated (per minute) as: ",
                                       "$$ \\frac{mean(abs(realDistance - eta))}{ (realDistance + eta) / 2 } $$"))),
                   plotOutput("mape", height="540px")))
)))
